name: "Description based Labeler"
on:
  pull_request_target:
    types: [opened, edited]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Check Labels
      id: labeler
      uses: jimschubert/labeler-action@cfce1831f33e0e4604bbc4e6933eb2f56c2fa530
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}